// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHW4gG0GEKYCCcs0jQkFkqVa_oroc66Jw',
    appId: '1:769210075708:web:855782cf470ddf2cf25139',
    messagingSenderId: '769210075708',
    projectId: 'freshtoday-app',
    authDomain: 'freshtoday-app.firebaseapp.com',
    storageBucket: 'freshtoday-app.firebasestorage.app',
    measurementId: 'G-Y89FFKP5RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVL5jk-wcC_zCKdqMvPcRhI_VewpnMDo8',
    appId: '1:769210075708:android:32f3a69c4b4ff368f25139',
    messagingSenderId: '769210075708',
    projectId: 'freshtoday-app',
    storageBucket: 'freshtoday-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv0B-qZQ28bclP-chGe0Ev5ypISAfLcmM',
    appId: '1:769210075708:ios:90ec0f84fb2f98a1f25139',
    messagingSenderId: '769210075708',
    projectId: 'freshtoday-app',
    storageBucket: 'freshtoday-app.firebasestorage.app',
    iosBundleId: 'com.example.freshtoday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv0B-qZQ28bclP-chGe0Ev5ypISAfLcmM',
    appId: '1:769210075708:ios:90ec0f84fb2f98a1f25139',
    messagingSenderId: '769210075708',
    projectId: 'freshtoday-app',
    storageBucket: 'freshtoday-app.firebasestorage.app',
    iosBundleId: 'com.example.freshtoday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHW4gG0GEKYCCcs0jQkFkqVa_oroc66Jw',
    appId: '1:769210075708:web:4c8b3faba35b76ebf25139',
    messagingSenderId: '769210075708',
    projectId: 'freshtoday-app',
    authDomain: 'freshtoday-app.firebaseapp.com',
    storageBucket: 'freshtoday-app.firebasestorage.app',
    measurementId: 'G-CEH3598YLB',
  );
}
